language: ruby
rvm:
  - 2.6

before_install:
  - nvm install stable

script:
  - bundle exec jekyll build
  - bundle exec htmlproofer
      --assume_extension --root-folder _site
      --allow_hash_href
      --typhoeus_config '{"timeout":60}'
      --http-status-ignore '0,301,302,403,410,429,500,501,502,503,522,999'
      _site
      || true
  # Lock the yaspeller version.
  # This will prevent spell checks from suddenly failing if yaspeller
  # e.g. (purely hypothetically *cough*) adds a fuzzier typo checker.
  - npm install yaspeller@6.0.*
  - npm install yaspeller-ci@1.0.2
  - npx yaspeller-ci --dictionary dictionary.json **/*.md || true

before_deploy:
  - pushd _site
  - rm CNAME | true
  - touch .nojekyll
  - popd

deploy:
  # Publish the staging branch to solid.github.io
  - provider: pages
    on:
      branch: staging
    local_dir: _site
    repo: solid/solid.github.io
    target_branch: master
    skip_cleanup: true
    keep_history: true
    allow_empty_commit: true
    github_token: $GITHUB_TOKEN
